### ISSUE TITLE
Support for 'beforeChange' listeners

### ISSUE THREAD

**Issue by laurens94** [tinymins/vue-photoswipe.js#1]
Hi! Is it possible to add a listener to events like `beforeChange`? It would be very helpful if the original photoswipe event listeners could be added, so it can be used like this: 

`this.$photoswipe.listen('beforeChange', function() { });`

Or is there a workaround to achieve the same functionality? 😄 

Thanks!

**Comment by tinymins** [comment]
Supported, please update to v2.0.16. https://github.com/tinymins/vue-photoswipe.js/commit/dd3cb3e61412bb94ad1aeafd9faf9f0c7b78bbb6 

Thanks for your advice. 😸

**Comment by laurens94** [comment]
Wow that was fast, thanks again!! 🥳
